# Generated by Django 3.1.3 on 2020-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documment_name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(max_length=3)),
                ('doc_format', models.TextField()),
                ('doc_type_page', models.CharField(max_length=2)),
                ('created_sub', models.DateTimeField(auto_now_add=True)),
                ('update_sub', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('company', models.TextField()),
                ('comments', models.TextField()),
                ('created_proj', models.DateTimeField(auto_now_add=True)),
                ('update_proj', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('created_sub', models.DateTimeField(auto_now_add=True)),
                ('update_sub', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
