# Generated by Django 3.1.3 on 2020-12-05 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskproject', '0002_auto_20201204_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotation',
            name='cod_doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskproject.doct'),
        ),
        migrations.AlterField(
            model_name='cotation',
            name='doc_name_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskproject.documentstandard'),
        ),
        migrations.AlterField(
            model_name='cotation',
            name='format_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskproject.pageformat'),
        ),
        migrations.AlterField(
            model_name='cotation',
            name='page_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskproject.paget'),
        ),
        migrations.AlterField(
            model_name='cotation',
            name='proj_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskproject.myproject'),
        ),
        migrations.AlterField(
            model_name='cotation',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskproject.subject'),
        ),
    ]
