# Generated by Django 3.1.3 on 2020-11-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskproject', '0002_auto_20201113_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='company',
            field=models.CharField(max_length=255),
        ),
    ]
