# Generated by Django 3.1.3 on 2020-11-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskproject', '0003_auto_20201114_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentstandard',
            old_name='created_sub',
            new_name='created_doc',
        ),
        migrations.RenameField(
            model_name='documentstandard',
            old_name='update_sub',
            new_name='update_doc',
        ),
    ]
