# Generated by Django 3.1.3 on 2020-11-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskproject', '0004_auto_20201114_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=12)),
                ('created_st', models.DateTimeField(auto_now_add=True)),
                ('update_st', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_office', models.CharField(max_length=255)),
                ('emp_contrato', models.CharField(max_length=20)),
                ('created_emp', models.DateTimeField(auto_now_add=True)),
                ('update_emp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatuDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_status', models.CharField(max_length=50)),
                ('created_st', models.DateTimeField(auto_now_add=True)),
                ('update_st', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
