# Generated by Django 3.1.3 on 2020-11-15 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskproject', '0005_action_employee_statudoc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatuDoc',
            new_name='StatusDoc',
        ),
    ]
