# Generated by Django 3.1.3 on 2020-11-15 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskproject', '0006_auto_20201115_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_page', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('qt_doc', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('qt_hh', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('created_ct', models.DateTimeField(auto_now_add=True)),
                ('update_ct', models.DateTimeField(auto_now=True)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskproject.documentstandard')),
                ('proj_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskproject.myproject')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskproject.subject')),
            ],
        ),
    ]
