# Generated by Django 3.1.3 on 2020-11-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskproject', '0009_auto_20201117_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arq', models.FileField(upload_to='xlsx/')),
                ('update_ct', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
