# Generated by Django 3.1.3 on 2020-11-21 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskproject', '0012_auto_20201118_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotation',
            name='cost_hh',
        ),
    ]
