# Generated by Django 3.1.3 on 2020-11-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskproject', '0013_remove_cotation_cost_hh'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_by_hh', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('cost_by_doc', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('cost_by_A1', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
    ]
